services:
  - type: web
    name: liga-campos-praticos
    runtime: python
    region: oregon
    plan: free

    buildCommand: pip install -r requirements.txt && python builder3.py
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 60

    envVars:
      - key: FLASK_ENV
        value: production
